version: '3.9'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: bookshelf
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - bookshelf-net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bookshelf-springboot
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/bookshelf?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - bookshelf-net

volumes:
  db_data:

networks:
  bookshelf-net:
